baseURL = "https://gokarna-hugo.netlify.app"
title = "Rihaan B H"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "AmFoss"
  description = "Hello There!!,This is Rihaan I am a first year student of Robotics and Artificial Engineering at Amrita University -Amritapuri Campus"
  avatarURL = "/images/avatar.webp"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
  
    {name = "linkedin", url = "https://www.linkedin.com/in/rihaan-b-h-6671b5288"},
    {name = "instagram", url = "https://instagram.com/rihaan_180?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D"},
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1
    
  [[menu.main]]
    name = "AboutMe"
    pre = "<span data-feather='user'></span>"
    url = "/About/"
    weight = 2


  [[menu.main]]
    name = "Blogs"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 3

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/RihaanBH-1810/amfoss-tasks.git"
    weight = 5


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
